name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black ruff
      - name: Lint (ruff)
        run: |
          ruff check .
      - name: Check formatting (black)
        run: |
          black --check .
      - name: Run tests
        run: |
          pytest -q
